language: python
sudo: false

python:
  - 3.4

install:
  - pip install .
  - pip install coverage python-coveralls

script:
  nosetests --with-coverage --cover-package=pycaching

after_success:
  coveralls