language: python

matrix:
  include:
    # Linux runners.
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
    # Windows runners.
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell  # `language: python` is not supported for now.
      before_install:
        - choco install python --version 3.7.7
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - python3 setup.py build install
  - pip install python-coveralls

script:
  python3 setup.py lint test

after_success:
  coveralls

deploy:
  provider: pypi
  skip_existing: true
  user: tomasbedrich
  password:
    secure: AmAJqaSOJprmoh4l7pLcDcRn2JRyAN6VbrFyezYmdHTd27jECIfm6jDPUo7N+PldUIxas5KonLxeJMF0Xx9vqr/HWwBSZo0e5JWs2+E5luFRF1Evw22VfNpyRQawHB2a47SUUTR82sypGF2v/mgeJJioSuIKo4o0KZ450zUoeM4=
  on:
    tags: true
    branch: master
    python: 3.6
  distributions: sdist bdist_wheel bdist_egg
